Repository inf112-v20/Robois, pull requests merged in 2020-05, with the labels that each got.

#29 Refactored how rendering works, and improved how boards are retrieved.
  src/main/java/inf112/skeleton/app/Game.java
  src/main/java/inf112/skeleton/app/GameRendering.java
  src/main/java/inf112/skeleton/app/Main.java
  src/main/java/inf112/skeleton/app/Player.java
  src/main/java/inf112/skeleton/app/assets/boards/b1.csv
  src/main/java/inf112/skeleton/app/assets/sprites/5.png
  src/main/java/inf112/skeleton/app/assets/sprites/backup.png
  src/main/java/inf112/skeleton/app/assets/sprites/move1.png
  src/main/java/inf112/skeleton/app/assets/sprites/move2.png
  src/main/java/inf112/skeleton/app/assets/sprites/move3.png
  src/main/java/inf112/skeleton/app/assets/sprites/rotateleft.png
  src/main/java/inf112/skeleton/app/assets/sprites/rotateright.png
  src/main/java/inf112/skeleton/app/assets/sprites/uturn.png
  src/main/java/inf112/skeleton/app/objects/Board.java
  src/main/java/inf112/skeleton/app/ui_objects/IRenderable.java
  src/main/java/inf112/skeleton/app/ui_objects/Panel.java
  src/main/java/inf112/skeleton/app/ui_objects/ProgramCard.java
  src/main/java/inf112/skeleton/app/ui_objects/ProgramCardHand.java
  src/main/java/inf112/skeleton/app/ui_objects/ProgramCardLocked.java
  src/main/java/inf112/skeleton/app/ui_objects/ProgramCardType.java
  src/main/java/inf112/skeleton/app/ui_objects/UIBoard.java
  src/main/java/inf112/skeleton/app/utilities/CsvReader.java
  src/main/java/inf112/skeleton/app/utilities/TextureReader.java
  src/test/java/inf112/skeleton/app/boardtests/BoardShould.java
Labels: Improvement, Introduction, Refactoring

#31 Phase turn implementation
  src/main/java/inf112/skeleton/app/Game.java
  src/main/java/inf112/skeleton/app/GamePhase.java
  src/main/java/inf112/skeleton/app/GameRendering.java
  src/main/java/inf112/skeleton/app/Main.java
  src/main/java/inf112/skeleton/app/Player.java
  src/main/java/inf112/skeleton/app/assets/boards/b1.csv
  src/main/java/inf112/skeleton/app/objects/Board.java
  src/main/java/inf112/skeleton/app/objects/Robot.java
  src/main/java/inf112/skeleton/app/objects/tiles/Beam.java
  src/main/java/inf112/skeleton/app/objects/tiles/Flag.java
  src/main/java/inf112/skeleton/app/objects/tiles/Gear.java
  src/main/java/inf112/skeleton/app/objects/tiles/Laser.java
  src/main/java/inf112/skeleton/app/objects/tiles/Pusher.java
Labels: Introduction

#54 Added the main game loop.
  src/main/java/inf112/skeleton/app/Game.java
  src/main/java/inf112/skeleton/app/GameLoop.java
  src/main/java/inf112/skeleton/app/GamePhase.java
  src/main/java/inf112/skeleton/app/GameRendering.java
  src/main/java/inf112/skeleton/app/Player.java
  src/main/java/inf112/skeleton/app/assets/boards/b_re.csv
  src/main/java/inf112/skeleton/app/assets/sprites/arrow_button.png
  src/main/java/inf112/skeleton/app/objects/Board.java
  src/main/java/inf112/skeleton/app/objects/abstracts/Move.java
  src/main/java/inf112/skeleton/app/objects/tiles/Laser.java
  src/main/java/inf112/skeleton/app/ui_objects/ProgramCardLocked.java
  src/main/java/inf112/skeleton/app/ui_objects/StartRoundButton.java
  src/main/java/inf112/skeleton/app/ui_objects/UIBoard.java
Labels: Improvement, Introduction, Refactoring

#59 Finishing game rule functionality
  README.md
  src/main/java/inf112/skeleton/app/Game.java
  src/main/java/inf112/skeleton/app/GameInput.java
  src/main/java/inf112/skeleton/app/GameLoop.java
  src/main/java/inf112/skeleton/app/GameMovement.java
  src/main/java/inf112/skeleton/app/GamePhase.java
  src/main/java/inf112/skeleton/app/GameRendering.java
  src/main/java/inf112/skeleton/app/Player.java
  src/main/java/inf112/skeleton/app/assets/boards/b_re.csv
  src/main/java/inf112/skeleton/app/objects/Board.java
  src/main/java/inf112/skeleton/app/objects/Robot.java
  src/main/java/inf112/skeleton/app/objects/interfaces/IMovable.java
  src/main/java/inf112/skeleton/app/ui_objects/EndGameDisplay.java
Labels: Improvement, Introduction

#60 Improved UI
  src/main/java/inf112/skeleton/app/GameRendering.java
  src/main/java/inf112/skeleton/app/assets/sprites/ui_background.png
  src/main/java/inf112/skeleton/app/ui_objects/ProgramCardLocked.java
Labels: Improvement
