Repository inf112-v20/Robois, pull requests merged in 2020-03, with the labels that each got.

#13 Optimized markdown quality
  Deliverables/ObligatoriskOppgave1.md
  deliverables/Oblig2.md
Labels: documentation

#10 Created tests and implementation for falling in holes
  src/main/java/inf112/skeleton/app/assets/boards/b1.csv
  src/main/java/inf112/skeleton/app/objects/Board.java
  src/main/java/inf112/skeleton/app/objects/tiles/Hole.java
  src/main/java/inf112/skeleton/app/utilities/TextureReader.java
  src/test/java/inf112/skeleton/app/robottests/RobotShould.java
Labels: Introduction

#18 Robots can push each other
  src/main/java/inf112/skeleton/app/Game.java
  src/main/java/inf112/skeleton/app/GameMovement.java
  src/main/java/inf112/skeleton/app/objects/Board.java
  src/main/java/inf112/skeleton/app/objects/abstracts/Location.java
  src/main/java/inf112/skeleton/app/utilities/CardinalityUtility.java
  src/test/java/inf112/skeleton/app/robottests/RobotShould.java
Labels: Improvement, Introduction

#19 Test cleanup
  src/test/java/inf112/skeleton/app/boardtests/BoardShould.java
  src/test/java/inf112/skeleton/app/robottests/FallingShould.java
  src/test/java/inf112/skeleton/app/robottests/RobotShould.java
  src/test/java/inf112/skeleton/app/robottests/WallsShould.java
Labels: Refactoring

#20 Created a dynamic way of creating tiles, using a JSON file.
  .vscode/settings.json
  pom.xml
  src/main/java/inf112/skeleton/app/Game.java
  src/main/java/inf112/skeleton/app/assets/boards/b0.csv
  src/main/java/inf112/skeleton/app/assets/boards/b1.csv
  src/main/java/inf112/skeleton/app/assets/sprites/temp.png
  src/main/java/inf112/skeleton/app/assets/sprites/tilelocation.json
  src/main/java/inf112/skeleton/app/objects/Board.java
  src/main/java/inf112/skeleton/app/objects/tiles/Beam.java
  src/main/java/inf112/skeleton/app/objects/tiles/CBelt.java
  src/main/java/inf112/skeleton/app/objects/tiles/FCBelt.java
  src/main/java/inf112/skeleton/app/objects/tiles/Flag.java
  src/main/java/inf112/skeleton/app/objects/tiles/Gear.java
  src/main/java/inf112/skeleton/app/objects/tiles/Laser.java
  src/main/java/inf112/skeleton/app/objects/tiles/Pusher.java
  src/main/java/inf112/skeleton/app/objects/tiles/Wrench.java
  src/main/java/inf112/skeleton/app/utilities/JSONTexture.java
  src/main/java/inf112/skeleton/app/utilities/TextureReader.java
Labels: Improvement, Introduction, Refactoring

#21 Tile functionality
  src/main/java/inf112/skeleton/app/Game.java
  src/main/java/inf112/skeleton/app/GameMovement.java
  src/main/java/inf112/skeleton/app/assets/boards/b1.csv
  src/main/java/inf112/skeleton/app/assets/sprites/tilelocation.json
  src/main/java/inf112/skeleton/app/objects/tiles/Belt.java
  src/main/java/inf112/skeleton/app/objects/tiles/CBelt.java
  src/main/java/inf112/skeleton/app/objects/tiles/FCBelt.java
  src/main/java/inf112/skeleton/app/utilities/CardinalDirection.java
  src/main/java/inf112/skeleton/app/utilities/CardinalityUtility.java
Labels: Introduction, Refactoring
